In [31]:
import pandas as pd
import matplotlib as plt

In [32]:
df = pd.read_csv('imdb_top_1000.csv')

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [5]:
df = df.drop(columns= 'Poster_Link')

In [6]:
#quais são as produções com maior nota
filtro = df[['Series_Title', 'IMDB_Rating']].sort_values(by= 'IMDB_Rating', ascending= False)
filtro.head(10)

                                    Series_Title  IMDB_Rating
0                       The Shawshank Redemption          9.3
1                                  The Godfather          9.2
2                                The Dark Knight          9.0
3                         The Godfather: Part II          9.0
4                                   12 Angry Men          9.0
5  The Lord of the Rings: The Return of the King          8.9
6                                   Pulp Fiction          8.9
7                               Schindler's List          8.9
8                                      Inception          8.8
9                                     Fight Club          8.8

In [7]:
#quais são os filmes de Scorsese na lista?
filtro = df[df['Director'] == 'Martin Scorsese'][['Series_Title', 'IMDB_Rating']]
filtro.sort_values(by= 'IMDB_Rating', ascending= False)

                Series_Title  IMDB_Rating
15                Goodfellas          8.7
37              The Departed          8.5
111              Taxi Driver          8.3
145           Shutter Island          8.2
147  The Wolf of Wall Street          8.2
165                   Casino          8.2
173              Raging Bull          8.2
484             The Irishman          7.9
687       The King of Comedy          7.8
836              After Hours          7.7

In [8]:
#quais são os generos que mais aparecem na lista?
filtro = df.groupby('Genre')['Series_Title'].count()
filtro.sort_values(ascending=False).head()

Genre
Drama                     85
Drama, Romance            37
Comedy, Drama             35
Comedy, Drama, Romance    31
Action, Crime, Drama      30
Name: Series_Title, dtype: int64

In [10]:
#ou
top_generos = df['Genre'].value_counts().head()
print(top_generos)

Genre
Drama                     85
Drama, Romance            37
Comedy, Drama             35
Comedy, Drama, Romance    31
Action, Crime, Drama      30
Name: count, dtype: int64

In [11]:
#quais são os diretores com mais filmes na lista?
top_diretores = df['Director'].value_counts().head()
print(top_diretores)

Director
Alfred Hitchcock    14
Steven Spielberg    13
Hayao Miyazaki      11
Akira Kurosawa      10
Martin Scorsese     10
Name: count, dtype: int64

In [7]:
#quais são os filmes mais bem avaliados dos anos 80?
filtro80 = (df['Released_Year'] >= 1980) & (df['Released_Year'] <= 1989)
df80 = df[filtro80]
top10 = df80[['Series_Title', 'IMDB_Rating']].sort_values(by= 'IMDB_Rating', ascending = False).head(10)
print(top10)

                                       Series_Title  IMDB_Rating
16   Star Wars: Episode V - The Empire Strikes Back          8.7
45                            Nuovo Cinema Paradiso          8.5
46                                   Hotaru no haka          8.5
47                               Back to the Future          8.5
71                      Once Upon a Time in America          8.4
72                          Raiders of the Lost Ark          8.4
73                                      The Shining          8.4
104                               Full Metal Jacket          8.3
105                                    Idi i smotri          8.3
106                                          Aliens          8.3

In [8]:
#quais são os filmes mais bem avaliados dos anos 90?
filtro90 = (df['Released_Year'] >= 1990) & (df['Released_Year'] <= 1999)
df90 = df[filtro90]
top10 = df90[['Series_Title','IMDB_Rating']].sort_values(by='IMDB_Rating', ascending= False).head(10)
print(top10.sort_index())

                Series_Title  IMDB_Rating
0   The Shawshank Redemption          9.3
6               Pulp Fiction          8.9
7           Schindler's List          8.9
9                 Fight Club          8.8
11              Forrest Gump          8.8
14                The Matrix          8.7
15                Goodfellas          8.7
24       Saving Private Ryan          8.6
25            The Green Mile          8.6
26           La vita è bella          8.6

In [ ]:
#e dos anos 2000?
filtro2000 = (df['Released_Year'] >= 2000) & (df['Released_Year'] <= 2009)
df2000 = df[filtro2000]
top10 = df2000[['Series_Title','IMDB_Rating']].sort_values(by='IMDB_Rating', ascending= False).head(10)
print(top10)

                                         Series_Title  IMDB_Rating
2                                     The Dark Knight          9.0
5       The Lord of the Rings: The Return of the King          8.9
10  The Lord of the Rings: The Fellowship of the Ring          8.8
13              The Lord of the Rings: The Two Towers          8.7
22                                     Cidade de Deus          8.6
23                      Sen to Chihiro no kamikakushi          8.6
36                                       The Prestige          8.5
37                                       The Departed          8.5
38                                        The Pianist          8.5
39                                          Gladiator          8.5

In [12]:
#quais são os 5 diretores que mais faturaram em média, mas apenas
#considerando filmes que tenham uma nota do IMDB maior que 8.0
filtro = df[df['IMDB_Rating'] > 8.0][['Director', 'Gross']]
filtro['Gross'] = filtro['Gross'].str.replace(",", "").astype(float)
top_diretores = filtro.groupby('Director')['Gross'].mean().sort_values(ascending=False).head()
print(top_diretores)

Director
Anthony Russo    7.685942e+08
Roger Allers     4.227838e+08
David Yates      3.810112e+08
Peter Jackson    3.453140e+08
Todd Phillips    3.354513e+08
Name: Gross, dtype: float64

In [13]:
#limpando o 'min' da celula e transformando em
df['Runtime'] = df['Runtime'].str.replace(' min', '').astype(int)

In [14]:
#Qual é a média de nota (IMDB_Rating) dos 
#filmes que duram mais de 2 horas (120 min)

filtro = df[df['Runtime'] > 120]
media = filtro['IMDB_Rating'].mean()
print(f'A media é {media:.2f}')

A media é 8.01

In [ ]:
#quais os generos mais lucrativos
df['Gross'] = pd.to_numeric(df['Gross'].str.replace(',', ''), errors='coerce')

ranking_genero = df.groupby('Genre')['Gross'].sum().sort_values(ascending=False)

print("Os 3 Gêneros mais lucrativos (em milhões):")
print(ranking_genero.head(3) / 1_000_000)

Os 3 Gêneros mais lucrativos (em milhões):
Genre
Action, Adventure, Sci-Fi       5898.659459
Animation, Adventure, Comedy    4503.337598
Action, Adventure, Drama        2668.835626
Name: Gross, dtype: float64

In [16]:
#quais são os 10 diretores com maior media de nota de filmes?
medias_por_diretor = df.groupby('Director')['IMDB_Rating'].mean()
medias_por_diretor = medias_por_diretor.sort_values(ascending=False).head(10)
print(medias_por_diretor)

Director
Frank Darabont        8.95
Lana Wachowski        8.70
Irvin Kershner        8.70
Masaki Kobayashi      8.60
Fernando Meirelles    8.60
George Lucas          8.60
Sudha Kongara         8.60
Thomas Kail           8.60
Roberto Benigni       8.60
Milos Forman          8.50
Name: IMDB_Rating, dtype: float64

In [17]:
# e quais são os filmes do diretor com maior media?
diretor = df[df['Director'] == 'Frank Darabont']
filmes = diretor[['Series_Title', 'IMDB_Rating']].sort_values(by= 'IMDB_Rating', ascending = False)
print(filmes)

                Series_Title  IMDB_Rating
0   The Shawshank Redemption          9.3
25            The Green Mile          8.6